// *** ADMIN ACTIONS *** //

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const FETCH_START = 'FETCH_START';
export const FETCH_END = 'FETCH_END';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_CANCEL = 'FETCH_CANCEL';

export const ALERT = 'ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';


// *** EVENT ACTIONS *** //
export const SUBMIT_EVENT = 'SUBMIT_EVENT';
export const SUBMIT_EVENT_SUCCESS = 'SUBMIT_EVENT_SUCCESS';
export const SUBMIT_EVENT_FAIL = 'SUBMIT_EVENT_FAIL';
export const SUBMIT_EVENT_RESET = 'SUBMIT_EVENT_RESET';